// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZ_LRUat9GgDpyS3nrR9mi329iuDgoIc',
    appId: '1:425440122621:web:23ab06b2457a731e27d094',
    messagingSenderId: '425440122621',
    projectId: 'zoom-clone-a2ef4',
    authDomain: 'zoom-clone-a2ef4.firebaseapp.com',
    storageBucket: 'zoom-clone-a2ef4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhu1CbDy-n8ALcvd0JbkmGpP9rbMMtgs',
    appId: '1:425440122621:android:bc9977d28b662df227d094',
    messagingSenderId: '425440122621',
    projectId: 'zoom-clone-a2ef4',
    storageBucket: 'zoom-clone-a2ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEssJPOdFevobT5PUDe0zhfBE77AUL_20',
    appId: '1:425440122621:ios:1c45916d6f5f179a27d094',
    messagingSenderId: '425440122621',
    projectId: 'zoom-clone-a2ef4',
    storageBucket: 'zoom-clone-a2ef4.appspot.com',
    iosBundleId: 'com.example.auraTechwizard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEssJPOdFevobT5PUDe0zhfBE77AUL_20',
    appId: '1:425440122621:ios:1c45916d6f5f179a27d094',
    messagingSenderId: '425440122621',
    projectId: 'zoom-clone-a2ef4',
    storageBucket: 'zoom-clone-a2ef4.appspot.com',
    iosBundleId: 'com.example.auraTechwizard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZ_LRUat9GgDpyS3nrR9mi329iuDgoIc',
    appId: '1:425440122621:web:ae90fcbb12c15c0727d094',
    messagingSenderId: '425440122621',
    projectId: 'zoom-clone-a2ef4',
    authDomain: 'zoom-clone-a2ef4.firebaseapp.com',
    storageBucket: 'zoom-clone-a2ef4.appspot.com',
  );
}
